app {
  spark {
    master = ${?SPARK_MASTER}
  }

  hdfs {
    base-uri = "hdfs://namenode:8020"
    base-uri = ${?HDFS_BASE_URI}
  }

  paths {
    bronze-base = ${app.hdfs.base-uri}"/data/bronze"
    silver-base = ${app.hdfs.base-uri}"/data/silver"
    reject-base = ${app.hdfs.base-uri}"/data/reject"
  }

  read {
    header = true
    infer-schema = false
    delimiter = ","
  }

  write {
    mode = "overwrite"
    format = "parquet"
  }

  jdbc {
    url = "jdbc:postgresql://postgres-warehouse:5432/warehouse"
    url = ${?JDBC_URL}
    user = "warehouse_user"
    user = ${?JDBC_USER}
    password = "warehouse_pass"
    password = ${?JDBC_PASSWORD}
    driver = "org.postgresql.Driver"
  }
}
