app {
  hdfs {
    base-uri = "hdfs://localhost:9000"
  }

  paths {
    bronze-base = "${app.hdfs.base-uri}/data/bronze"
    silver-base = "${app.hdfs.base-uri}/data/silver"
    reject-base = "${app.hdfs.base-uri}/data/reject"
  }

  read {
    header = true
    infer-schema = false
    delimiter = ","
  }

  write {
    mode = "overwrite"
    format = "parquet"
  }

  jdbc {
    url = ${?JDBC_URL}
    user = ${?JDBC_USER}
    password = ${?JDBC_PASSWORD}
    driver = "org.postgresql.Driver"
  }
}